### PR TITLE
simple fix for #140

### LINKED ISSUE #140: Broadcasting and nested arrays (regression in ReverseDiff 1.4)
I've experienced what looks like a regression in ReverseDiff 1.4. The following code used to work fine in older versions but now if fails:
```julia
julia> using ReverseDiff

julia> g(u) = u[1] * [[1, 2], [4, 5]]
g (generic function with 1 method)

julia> ReverseDiff.gradient(g, [1.0])
ERROR: TypeError: in TrackedReal, in V, expected V<:Real, got Type{Array{Float64,1}}
Stacktrace:
 [1] ReverseDiff.TrackedArray(::Array{Array{Float64,1},1}, ::Array{Float64,1}, ::Array{ReverseDiff.AbstractInstruction,1}) at /home/mateusz/.julia/packages/ReverseDiff/tCOFA/src/tracked.jl:86
 [2] track(::Array{Array{Float64,1},1}, ::Type{Float64}, ::Array{ReverseDiff.AbstractInstruction,1}) at /home/mateusz/.julia/packages/ReverseDiff/tCOFA/src/tracked.jl:439
 [3] broadcast_mul(::ReverseDiff.TrackedReal{Float64,Float64,ReverseDiff.TrackedArray{Float64,Float64,1,Array{Float64,1},Array{Float64,1}}}, ::Array{Array{Int64,1},1}, ::Type{Float64}) at /home/mateusz/.julia/packages/ReverseDiff/tCOFA/src/derivatives/elementwise.jl:421
 [4] broadcast at /home/mateusz/.julia/packages/ReverseDiff/tCOFA/src/derivatives/elementwise.jl:342 [inlined]
 [5] _materialize at /home/mateusz/.julia/packages/ReverseDiff/tCOFA/src/derivatives/broadcast.jl:294 [inlined]
 [6] materialize at /home/mateusz/.julia/packages/ReverseDiff/tCOFA/src/derivatives/broadcast.jl:311 [inlined]
 [7] broadcast_preserving_zero_d at ./broadcast.jl:809 [inlined]
 [8] * at ./arraymath.jl:52 [inlined]
 [9] g(::ReverseDiff.TrackedArray{Float64,Float64,1,Array{Float64,1},Array{Float64,1}}) at ./REPL[15]:1
 [10] ReverseDiff.GradientTape(::typeof(g), ::Array{Float64,1}, ::ReverseDiff.GradientConfig{ReverseDiff.TrackedArray{Float64,Float64,1,Array{Float64,1},Array{Float64,1}}}) at /home/mateusz/.julia/packages/ReverseDiff/tCOFA/src/api/tape.jl:199
 [11] gradient(::Function, ::Array{Float64,1}, ::ReverseDiff.GradientConfig{ReverseDiff.TrackedArray{Float64,Float64,1,Array{Float64,1},Array{Float64,1}}}) at /home/mateusz/.julia/packages/ReverseDiff/tCOFA/src/api/gradients.jl:22 (repeats 2 times)
 [12] top-level scope at REPL[16]:1
```
Probably related to https://github.com/JuliaDiff/ReverseDiff.jl/pull/134 .

### PR DESCRIPTION
**Pull request by mateuszbaran**
This is my attempt to fix #140. The relevant test is here: https://github.com/JuliaDiff/DiffTests.jl/pull/10 and locally it passes.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Add that test here as well?

**Comment by mateuszbaran** [comment]
OK, I'll add that test here.

**Review by mohamed82008 — APPROVED** [review]
LGTM.

**Comment by mohamed82008** [comment]
Once the test is added, this can be merged.

**Comment by mateuszbaran** [comment]
I had to make an additional adjustment to make the tests pass on Julia 1.0. Additionally, if I use a random vector here: https://github.com/JuliaDiff/ReverseDiff.jl/pull/142/files#diff-516f2fc7e3b4733687c4f2f36918bd39R178 then one of further tests fails.

**Comment by mohamed82008** [comment]
Thanks @mateuszbaran! Sorry for the delayed merge :)

**Pull request merged**
