### PR TITLE
Bump version to 1.15.2

### PR DESCRIPTION
**Pull request by gdalle**

### CODE REVIEW

**Comment by devmotion** [comment]
I think we should merge #253 first which potentially fixes the docs.

**Comment by gdalle** [comment]
Merging either first doesn't make much difference, but yeah let's definitely wait for both PRs before registering the new version!

**Comment by devmotion** [comment]
Ah sorry, I forgot that you had merge rights in this repo! I'll let you merge the next time 🙂

**Comment by gdalle** [comment]
no big deal :) should we release?

**Pull request merged**
