### PR TITLE
broadcasting perf fix

### PR DESCRIPTION
**Pull request by mohamed82008**
This PR ports some code from DistributionsAD.jl to improve the performance of broadcasting in ReverseDiff allow for fused broadcast expressions with TrackedArray inputs to give a TrackedArray output where possible and provably correct. The implementation details and decisions are explained in https://github.com/TuringLang/DistributionsAD.jl/pull/58#issue-395068525. I still need to add some t ests.

### CODE REVIEW

**Comment by mohamed82008** [comment]
The test failure needs some work. I won't be able to come back to this for at least 3 days.

**Comment by ChrisRackauckas** [comment]
bump on this 😄

**Comment by mohamed82008** [comment]
Will get on it after I upload my JuliaCon presentation :)

**Comment by ChrisRackauckas** [comment]
Alright thanks!

**Comment by mohamed82008** [comment]
Sorry for the delay. I am on it.

**Comment by mohamed82008** [comment]
The test failure is a StackOverFlow when computing the Hessian of a function with broadcasting. Working on a fix.

**Comment by mohamed82008** [comment]
Tests should pass now.

**Pull request merged**
