### PR TITLE
Fix `vcat` method ambiguity issues on Julia 1.8

### PR DESCRIPTION
**Pull request by devmotion**
Fixes the `vcat` test errors due to a method ambiguity issue on Julia 1.8. These test errors are present on the master branch and show also up in other unrelated PRs.

Maybe at some point one should clean up the `vcat`/`hcat`/`cat` definitions, similar to https://github.com/FluxML/Tracker.jl/pull/128. But for now it seemed easier to just fix the reported method ambiguity issue.

### CODE REVIEW

**Comment by devmotion** [comment]
The test errors are known and caused by the latest release of DiffTests. I opened an issue and a PR a week ago.

**Comment by mohamed82008** [comment]
Can we upper bound the version of DiffTests?

**Comment by devmotion** [comment]
A bit unfortunate but I guess that's probably the fastest and easiest solution for now. I also checked https://github.com/JuliaDiff/DiffTests.jl/pull/15 with this PR locally, and while it seems to fix the current issues it still fails due to some newly uncovered ambiguity issues (e.g., `*(::Diagonal, ::TrackedMatrix)`).

**Comment by devmotion** [comment]
As expected, with DiffTests 0.1.1 all tests pass.

**Review by mohamed82008 — APPROVED** [review]

**Pull request merged**
